### ISSUE TITLE
How to configure different docker ports in one nexus-proxy

### ISSUE THREAD

**Issue by luoyan35714** [travelaudience/nexus-proxy#6]
How to configure different docker ports in one nexus-proxy?
Usually we defined 3 docker repository in one nexus, one for group, one for proxy, one for hosted. And we need the hosted port to push the image, we need the group port to pull the image. Then how to do that in nexus proxy?

**Comment by pires** [comment]
I don't have an answer for you. Let us know if you find a solution.

**Comment by luoyan35714** [comment]
Finally, we decided to stop using the nexus-proxy. We are specified the service to the nexus pod  directly and provided the HTTPs in the ingress. If any guys have a better choice, please update me. Thanks.
